version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./static:/app/static
    command: python -m backend.main
    env_file:
      - .env
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge